feat: Add Prop Types
sparkdesignsystem/spark-design-system pull request #3488
Opened 2020-09-30 23:09 UTC by hmajid2301

## What does this PR do?
Add missing prop types to `UsingSparkLayout.ts`
and eslint fixes as well.

### Associated Issue
Fixes #3478 

## Please check off completed items as you work.
If a checklist item or section does not apply to your PR then please remove it.

### Documentation
 - [x] Update Spark Docs

### Screenshots
Add screenshots to help explain your PR if you'd like. However, this is not
expected.

2020-10-01 15:31 UTC, guern1kn requested changes
Thank you! The UsingSparkLayout.js looks great. Could you remove the package-lock.json from the pr? We'll get it merged after that!

2020-10-01 21:08 UTC, hmajid2301 commented
Done!

2020-10-01 22:56 UTC, afebbraro approved these changes

2020-10-02 12:52 UTC, guern1kn approved these changes

2020-10-02 12:52 UTC, guern1kn commented
Thank you for contributing, @hmajid2301 !

2020-10-02 14:28 UTC, merged