Toggle Updates - React
sparkdesignsystem/spark-design-system pull request #3560
Opened 2020-10-12 16:01 UTC by guern1kn

## What does this PR do?
- Change isDefaultOpen to be isOpen and allow the consumer to be able to have the toggle open by default and also close/open it whenever.
- Update prop names for titleAddClasses and iconAddClasses. Follow the convention of elementAdditionalClasses. Change title to triggerText.
- Button element needs type=button
- Fix eslint errors
- add handler function prop to run when toggle is clicked
- change title prop to be triggerText since title causes a11y issues.
- add ability to add classes to the content

### Associated Issue
Fixes #3295 

## Please check off completed items as you work.
If a checklist item or section does not apply to your PR then please remove it.

### Documentation
 - [ ] Update Spark Docs

### Code
 - [ ] Build Component in HTML
 - [ ] Build Component in Angular
 - [ ] Build Component in React
 - [ ] Unit Testing in HTML with `npm run test` in `html/` (100% coverage, 100% passing)
 - [ ] Unit Testing in Angular with `npm run test` in `angular/` (100% coverage, 100% passing)
 - [ ] Unit Testing in React with `npm run test` in `react/` (100% coverage, 100% passing)

### Browser Testing (current version and 1 prior)
  - [ ] Google Chrome
  - [ ] Google Chrome (Mobile)
  - [ ] Mozilla Firefox
  - [ ] Mozilla Firefox (Mobile)
  - [ ] Microsoft Internet Explorer 11 (only this specific version of IE)
  - [ ] Microsoft Edge
  - [ ] Apple Safari
  - [ ] Apple Safari (Mobile)
  
### Accessibility Testing
  - [ ] Axe browser extension
  - [ ] Jaws Inspect
  - [ ] VoiceOver (iOS) or Talkback (Android)

### Deploy Preview Reviewed and Approved
 - [ ] Design Team
 - [ ] Accessibility Team

### Screenshots
Add screenshots to help explain your PR if you'd like. However, this is not
expected.

2020-10-13 20:22 UTC, RCopeland requested changes
made a couple suggestions

2020-10-13 20:22 UTC, RCopeland commented on react/src/components/toggle/SprkToggle.js
> +      height: isOpen ? 'auto' : 0,
i would assign the new isOpen from the old isDefaultOpen, then you dont have to have logic to check both:
```suggestion
    const {
      isDefaultOpen,
      isOpen = isDefaultOpen,
    } = this.props;

    this.state = {
      isOpen: isOpen || false,
      height: isOpen ? 'auto' : 0,
```

2020-10-13 20:22 UTC, RCopeland commented on react/src/components/toggle/SprkToggle.js
> +      titleAdditionalClasses || titleAddClasses,
dont need this check if you make the change above

2020-10-13 20:22 UTC, RCopeland commented on react/src/components/toggle/SprkToggle.js
> +      iconAdditionalClasses || iconAddClasses,
here too

2020-10-13 20:22 UTC, RCopeland commented on react/src/components/toggle/SprkToggle.js
> +              onClick();
```suggestion
              onClick(e);
```

2020-10-13 20:22 UTC, RCopeland commented on react/src/components/toggle/SprkToggle.js
> +          {triggerText || title}
dont need the check if you make the change above

2020-10-13 20:23 UTC, RCopeland commented
@guern1kn I also see the aria-controls and matching ids are incrementing when ever its toggled open. They still match, but its weird. I think its because the unique id generation happens in the render, you should move it up to the constructor probably and make it part of state instead.

2020-10-13 20:57 UTC, afebbraro requested changes

2020-10-13 20:57 UTC, afebbraro commented on react/src/components/toggle/SprkToggle.js
> +  /** Determines if the toggle is open upon loading on the page. */
hey @guern1kn , part of the a/c is that they can have it be open or closed whenever.  Lets update this prop description so it mentions that its not just on page load.

2020-10-13 21:01 UTC, afebbraro commented
@guern1kn the sprkaward component uses sprktoggle. Lets update that one line of 'title' in there too.

2020-10-14 20:18 UTC, bobwise requested changes

2020-10-14 20:18 UTC, bobwise commented on react/src/components/toggle/SprkToggle.js
> +      isOpen: isOpen || false,
Copying the prop into state in the constructor means any changes to the prop after init will be ignored.

2020-10-16 20:57 UTC, afebbraro approved these changes
Approved! Just need that update to the addclasses prop description then good for merge. Thanks.

2020-10-16 21:04 UTC, RCopeland approved these changes

2020-10-16 21:24 UTC, merged