Toggle Updates - Angular
sparkdesignsystem/spark-design-system pull request #3588
Opened 2020-10-19 14:34 UTC by guern1kn

## What does this PR do?
- [ ] Add ability to have the toggle content open by default and ability to close/open it whenever programmatically - match React naming isOpen.
- [x] add type=button
- [ ] change title prop to be triggerText since title causes a11y issues.
- [ ] add event emitter for when toggle opens or closes ex.
- [ ] add ability to enter a different icon name
- [ ] add ability to add different classes to the icon - iconAdditionalClasses
- [ ] add ability to add classes to the content - contentAdditionalClasses

### Associated Issue
Fixes #3296 

### Documentation
 - [ ] Update Spark Docs

### Code
 - [ ] Build Component in Angular
 - [ ] Unit Testing in Angular with `npm run test` in `angular/` (100% coverage, 100% passing)

### Browser Testing (current version and 1 prior)
  - [ ] Google Chrome
  - [ ] Google Chrome (Mobile)
  - [ ] Mozilla Firefox
  - [ ] Mozilla Firefox (Mobile)
  - [ ] Microsoft Internet Explorer 11 (only this specific version of IE)
  - [ ] Microsoft Edge
  - [ ] Apple Safari
  - [ ] Apple Safari (Mobile)
  
### Accessibility Testing
  - [ ] Axe browser extension
  - [ ] Jaws Inspect
  - [ ] VoiceOver (iOS) or Talkback (Android)

### Deploy Preview Reviewed and Approved
 - [ ] Design Team
 - [ ] Accessibility Team

### Screenshots
Add screenshots to help explain your PR if you'd like. However, this is not
expected.

2020-10-20 18:46 UTC, bobwise commented on angular/projects/spark-angular/src/lib/components/sprk-toggle/sprk-toggle.component.ts
>     * rendered as the main Toggle link text.
```suggestion
   * rendered as the main Toggle button text.
```

2020-10-20 18:46 UTC, bobwise commented on angular/projects/spark-angular/src/lib/components/sprk-toggle/sprk-toggle.component.ts
> +   * rendered as the main Toggle link text.
```suggestion
   * rendered as the main Toggle button text.
```

2020-10-20 18:46 UTC, bobwise commented on angular/projects/spark-angular/src/lib/components/sprk-toggle/sprk-toggle.component.ts
> +    }
I like this much better than the previous version!

2020-10-20 18:57 UTC, RVMendoza commented on angular/projects/spark-angular/src/lib/components/sprk-toggle/sprk-toggle.component.spec.ts
> +  it('should render open if isOpen is set to true', () => {
This is all semantics, but I wonder if this test is really "should load correct classes if isOpen is set to true"

2020-10-20 20:00 UTC, bobwise approved these changes

2020-10-21 19:00 UTC, afebbraro requested changes

2020-10-21 19:00 UTC, afebbraro commented on angular/projects/spark-angular/src/lib/components/sprk-toggle/sprk-toggle.component.ts
> +  titleAdditionalClasses: string;
hey @guern1kn , In going through this, a light bulb went off haha. If we change title to heading we have to change the other names too like titleAdditionalClasses

2020-10-21 19:50 UTC, bobwise approved these changes

2020-10-21 19:50 UTC, bobwise commented on angular/projects/spark-angular/src/lib/components/sprk-toggle/sprk-toggle.component.spec.ts
> +    expect(triggerElement.getAttribute('aria-expanded')).toEqual('true');
🎉

2020-10-21 20:05 UTC, RVMendoza approved these changes

2020-10-21 20:20 UTC, afebbraro approved these changes

2020-10-21 20:20 UTC, merged