Fix uniqueIds from incrementing on toggle
sparkdesignsystem/spark-design-system pull request #3608
Opened 2020-10-29 19:32 UTC by guern1kn

## What does this PR do?
Updates the uniqueIds in SprkToggle and SprkMastheadAccordionItem to be unique if there are multiple on the same page, but not increment on toggle.

### Associated Issue
Fixes #3598 

## Please check off completed items as you work.
If a checklist item or section does not apply to your PR then please remove it.

### Code
 - [x] Build Component in React
 - [x] Unit Testing in React with `npm run test` in `react/` (100% coverage, 100% passing)

### Browser Testing (current version and 1 prior)
  - [x] Google Chrome
  - [ ] Google Chrome (Mobile)
  - [ ] Mozilla Firefox
  - [ ] Mozilla Firefox (Mobile)
  - [ ] Microsoft Internet Explorer 11 (only this specific version of IE)
  - [ ] Microsoft Edge
  - [ ] Apple Safari
  - [ ] Apple Safari (Mobile)

### Screenshots
![image](https://user-images.githubusercontent.com/15703773/97623361-eab2bc80-19fb-11eb-95a3-b29aca6a4eb7.png)

2020-11-02 20:44 UTC, bobwise requested changes
Great job on this bug fix! I just left a couple comments.

2020-11-02 20:44 UTC, bobwise commented on react/src/components/masthead/components/SprkMastheadAccordionItem/SprkMastheadAccordionItem.test.js
>    });
Great job on this fix! It looks like we already have tests to make sure a provided `id` is not overwritten by a calculated `id` - can we get a new test to make sure the id doesn't change when we toggle?

2020-11-02 20:44 UTC, bobwise commented on react/src/components/toggle/SprkToggle.test.js
>      );
Same feedback as Masthead - let's make sure to add a new test to verify that the ID doesn't change on toggle.

2020-11-02 21:50 UTC, bobwise commented on react/src/components/toggle/SprkToggle.test.js
> +    const ButtonAriaControls = wrapper.find('button').prop('aria-controls');
```suggestion
    const buttonAriaControls = wrapper.find('button').prop('aria-controls');
```

2020-11-02 21:50 UTC, bobwise commented on react/src/components/toggle/SprkToggle.test.js
> +    expect(toggleContentId).toEqual(ButtonAriaControls);
```suggestion
    expect(toggleContentId).toEqual(buttonAriaControls);
```

2020-11-02 21:51 UTC, bobwise commented on react/src/components/toggle/SprkToggle.test.js
> +    expect(ButtonAriaControls).toEqual(postClickToggleContentId);
```suggestion
    expect(buttonAriaControls).toEqual(postClickToggleContentId);
```

2020-11-02 21:51 UTC, bobwise approved these changes

2020-11-02 21:51 UTC, bobwise commented on react/src/components/toggle/SprkToggle.test.js
> +    const ButtonAriaControls = wrapper.find('button').prop('aria-controls');
I think this should be lowercase.

2020-11-03 14:11 UTC, RCopeland approved these changes
lgtm

2020-11-03 14:22 UTC, merged