update select input to use forwardedRef
sparkdesignsystem/spark-design-system pull request #3728
Opened 2020-12-23 21:05 UTC by Adrean1983

## What does this PR do?
Passed forwardedRef as a propType to the component. Assigned the forwaredRef to selectRef.

### Associated Issue
Fixes 1361

2020-12-27 23:59 UTC, afebbraro commented
hey @Adrean1983 , thanks for the PR. I'm sorry but we aren't able to accept this PR as is because this component is used for more than `<select>` elements. This means that having the `forwardedRef` prop as an option on the component but only having it work on `<select>` elements would cause confusion for someone who is using the prop in conjunction with the `variant` prop set to radio or checkbox. If you'd like, you can update this PR with that or I can close this PR and we will address the issue soon. Thanks again for the PR and bringing up the missing opportunity for having an option to attach a ref here.

2020-12-28 19:34 UTC, afebbraro requested changes
Left a comment about changes.

2021-01-04 20:05 UTC, afebbraro commented
hey @Adrean1983 ! Hope you had a great holiday break. I wanted to check in to see if you had a chance to read my comment on this PR. Let me know if you have any questions.

2021-01-05 01:31 UTC, Adrean1983 commented
> hey @Adrean1983 ! Hope you had a great holiday break. I wanted to check in to see if you had a chance to read my comment on this PR. Let me know if you have any questions.

Hey! I'm on a break too. I think we decided just to wait for the Spark team to wrap up the PR. It seemed like something that would need to be engineered for other components and I was not sure what approach to take.

2021-01-12 23:59 UTC, afebbraro commented
Cool that sounds good. We'll reach out once its fixed! Thanks again. @Adrean1983

2021-01-12 23:59 UTC, closed without merging