Update Huge stories
sparkdesignsystem/spark-design-system pull request #3744
Opened 2021-01-07 17:14 UTC by guern1kn

## What does this PR do?
A clear and concise description of what this PR does.

### Associated Issue
Fixes #3743 

## Please check off completed items as you work.
If a checklist item or section does not apply to your PR then please remove it.

### Documentation
 - [ ] Update Spark Docs

### Code
 - [ ] Build Component in HTML
 - [ ] Build Component in Angular
 - [ ] Build Component in React
 - [ ] Unit Testing in HTML with `npm run test` in `html/` (100% coverage, 100% passing)
 - [ ] Unit Testing in Angular with `npm run test` in `angular/` (100% coverage, 100% passing)
 - [ ] Unit Testing in React with `npm run test` in `react/` (100% coverage, 100% passing)

### Browser Testing (current version and 1 prior)
  - [ ] Google Chrome
  - [ ] Google Chrome (Mobile)
  - [ ] Mozilla Firefox
  - [ ] Mozilla Firefox (Mobile)
  - [ ] Microsoft Internet Explorer 11 (only this specific version of IE)
  - [ ] Microsoft Edge
  - [ ] Apple Safari
  - [ ] Apple Safari (Mobile)
  
### Accessibility Testing
  - [ ] Axe browser extension
  - [ ] Jaws Inspect
  - [ ] VoiceOver (iOS) or Talkback (Android)

### Deploy Preview Reviewed and Approved
 - [ ] Design Team
 - [ ] Accessibility Team

### Screenshots
Add screenshots to help explain your PR if you'd like. However, this is not
expected.

2021-01-08 16:22 UTC, bobwise reviewed
Great work on this @guern1kn! Do you think we should add Huge Date Picker to input.mdx?

2021-01-08 19:01 UTC, bobwise approved these changes

2021-01-12 18:17 UTC, afebbraro requested changes
This just needs the the redirects and the story names to match. Other than that looks good! Thank you for doing this!

2021-01-13 00:00 UTC, afebbraro approved these changes
Thanks for getting this in!

2021-01-13 00:01 UTC, merged