SprkTextInput aria-describedby
sparkdesignsystem/spark-design-system pull request #3784
Opened 2021-01-19 21:38 UTC by bobwise

Modifies SprkTextInput to only include `aria-describedby` on the `<input>` if it has an error container.

### Associated Issue
Fixes #3526 

### Code
 - [ ] Build Component in React
 - [ ] Unit Testing in React with `npm run test` in `react/` (100% coverage, 100% passing)

### Browser Testing (current version and 1 prior)
  - [ ] Google Chrome
  - [ ] Google Chrome (Mobile)
  - [ ] Mozilla Firefox
  - [ ] Mozilla Firefox (Mobile)
  - [ ] Microsoft Internet Explorer 11 (only this specific version of IE)
  - [ ] Microsoft Edge
  - [ ] Apple Safari
  - [ ] Apple Safari (Mobile)
  
### Accessibility Testing
  - [ ] Axe browser extension
  - [ ] Jaws Inspect
  - [ ] VoiceOver (iOS) or Talkback (Android)

### Deploy Preview Reviewed and Approved
 - [ ] Design Team
 - [ ] Accessibility Team

### Screenshots
Add screenshots to help explain your PR if you'd like. However, this is not
expected.

2021-01-20 13:14 UTC, afebbraro requested changes
aria-described by could be used for more use cases besides the field being invalid. If we only allow it if there’s an error container then we could be restricting use. What do you think?

2021-01-20 14:23 UTC, guern1kn approved these changes
I think that @afebbraro has a good point, but I think it's fine the way it currently is. We are currently setting the `errorContainerId` internally and passing it to the `<SprkInputElement>`. Both the `<SprkTextInput>` and `<SprkInputElement>` are in the process of being replaced. I don't know that it makes sense to spend time re-writing these components to allow for additional functionality at this point. Amber's point would be something to keep in mind for the React Input API upgrades though.

2021-01-20 14:31 UTC, bobwise commented
Yes @afebbraro is correct. `aria-describedby` can actually have multiple values passed into it at the same time, which Spark should support. Spark should be putting the helper text container id in the `aria-describedby` as well as allowing users to add their own. This is one of the items that came up in our accessibility audit (HTML framework). https://github.com/sparkdesignsystem/Backlog/issues/1332

2021-01-20 18:49 UTC, RVMendoza commented on react/src/base/inputs/SprkTextInput/SprkTextInput.js
> +              errorContainerId={valid ? undefined : errorContainerId}
Nice! This is a good way to make sure screen readers aren't confused if the error doesn't exist.

2021-01-20 18:49 UTC, RVMendoza approved these changes

2021-01-24 00:15 UTC, afebbraro commented
@bobwise  If we want to fix the bug and not introduce new a11y errors, it would be best to update this component to accept an ariaDescribedBy prop that if it has a value would pass down to the input element component and additionally, if the input is also invalid it would join errorContainerId and the ariaDescribedBy into a string that it would pass down. That away, users can supply their own ariaDescribedBy and we would also linking the error container correctly.

2021-01-25 19:57 UTC, guern1kn approved these changes

2021-01-25 20:35 UTC, RVMendoza approved these changes

2021-01-25 20:36 UTC, RVMendoza commented on react/src/base/inputs/components/SprkInputElement/SprkInputElement.js
> +    const getAriaDescribedBy = () => {
nice! this is definitely something we should be incorporating to our other components that use aria-describedby

2021-01-28 00:19 UTC, afebbraro commented on react/src/base/inputs/components/SprkInputElement/SprkInputElement.js
> +        aria-describedby={getAriaDescribedBy()}
Thanks for adding this. I did notice a potential issue. This seems to be running every time the component renders for me, so even though the errorcontainer /id hasnt changed this gets triggered. Every time I type a character in the input, it runs. Which seems to drag down performance. Maybe I am doing something weird? But thats what I am seeing.  I think something to try here would be to bind this to a method that runs on one of the lifecycle hooks, componentDidMount() ?

2021-01-29 18:39 UTC, afebbraro approved these changes

2021-01-29 20:04 UTC, merged