React Dropdown API Upgrades
sparkdesignsystem/spark-design-system pull request #3794
Opened 2021-01-21 22:34 UTC by bobwise

## What does this PR do?
A clear and concise description of what this PR does.

### Associated Issue
Fixes (Issue Number that this PR is closing out)

## Please check off completed items as you work.
If a checklist item or section does not apply to your PR then please remove it.

### Documentation
 - [ ] Update Spark Docs

### Code
 - [ ] Build Component in HTML
 - [ ] Build Component in Angular
 - [ ] Build Component in React
 - [ ] Unit Testing in HTML with `npm run test` in `html/` (100% coverage, 100% passing)
 - [ ] Unit Testing in Angular with `npm run test` in `angular/` (100% coverage, 100% passing)
 - [ ] Unit Testing in React with `npm run test` in `react/` (100% coverage, 100% passing)

### Browser Testing (current version and 1 prior)
  - [ ] Google Chrome
  - [ ] Google Chrome (Mobile)
  - [ ] Mozilla Firefox
  - [ ] Mozilla Firefox (Mobile)
  - [ ] Microsoft Internet Explorer 11 (only this specific version of IE)
  - [ ] Microsoft Edge
  - [ ] Apple Safari
  - [ ] Apple Safari (Mobile)
  
### Accessibility Testing
  - [ ] Axe browser extension
  - [ ] Jaws Inspect
  - [ ] VoiceOver (iOS) or Talkback (Android)

### Deploy Preview Reviewed and Approved
 - [ ] Design Team
 - [ ] Accessibility Team

### Screenshots
Add screenshots to help explain your PR if you'd like. However, this is not
expected.

2021-01-25 16:27 UTC, guern1kn commented on react/src/components/dropdown/SprkDropdown.js
>            data-id={idString || 'undefined'}
I know this wasn't part of the AC, but we should update this. If there isn't an `analyticsString` or `data-id` they shouldn't be added.

2021-01-25 16:51 UTC, guern1kn commented on react/src/components/dropdown/SprkDropdown.test.js
>  });
Let's add tests for the new prop names.

2021-01-25 16:54 UTC, guern1kn commented on react/src/components/dropdown/SprkDropdown.js
>                  "
We should allow the `iconAddiontionalClasses` to be added to both the default and informational variants.

2021-01-25 16:55 UTC, guern1kn commented on react/src/components/dropdown/SprkDropdown.js
>              <>
Update this to be `triggerTextAdditionalClasses`

2021-01-25 17:02 UTC, guern1kn commented on react/src/components/dropdown/SprkDropdown.js
>                            <p className="sprk-b-TypeBodyTwo">
If an `infoLine` isn't present in the `item.content` then an empty `<p>` still gets rendered. Let's add some checks to only render what's necessary.

2021-01-25 17:05 UTC, guern1kn requested changes
Nice work on this, Bob. Left a few comments. I feel like there's still quite a few elements of this that we could improve on customization, like adding extra classes. For example, `footerAdditionalClasses`. What are your thoughts on adding some more props like that?

2021-01-25 20:15 UTC, bobwise commented
> Nice work on this, Bob. Left a few comments. I feel like there's still quite a few elements of this that we could improve on customization, like adding extra classes. For example, `footerAdditionalClasses`. What are your thoughts on adding some more props like that?

Thanks @guern1kn! I agree there are a lot of parts of this component that can't currently be customized. There are comments in the original Issue that indicate that we are comfortable with the current level of customization.

> Dropdowns use a config object to build the dropdown items. That method seems to be okay here for now because they aren't a highly customizable component (such as cards).

This would be a good thing to bring up to the whole group I think. I'd rather refactor it into a compositional component than try to add 2-5 new `additionalClasses` props at this point.

2021-01-28 16:36 UTC, guern1kn approved these changes
lgtm

2021-01-28 19:24 UTC, afebbraro requested changes
Hey @bobwise , with the router issue recently, we need to make sure all our components support router links. I tried with this and it doesnt work, i get this error Warning: Failed prop type: Invalid prop `choices.items[0].element` supplied to `SprkDropdown`.

I updated the AC for this component. Should hopefully be an easy addition to this PR.

2021-01-29 22:10 UTC, afebbraro approved these changes
Looks great, thank you for incorporating the browser router.

2021-01-29 22:19 UTC, guern1kn approved these changes

2021-02-01 15:06 UTC, merged