Add ability to use routerLinks in masthead
sparkdesignsystem/spark-design-system pull request #3826
Opened 2021-02-01 19:43 UTC by afebbraro

## What does this PR do?
A clear and concise description of what this PR does.

### Associated Issue
Fixes (Issue Number that this PR is closing out)

## Please check off completed items as you work.
If a checklist item or section does not apply to your PR then please remove it.

### Documentation
 - [ ] Update Spark Docs

### Code
 - [ ] Build Component in HTML
 - [ ] Build Component in Angular
 - [ ] Build Component in React
 - [ ] Unit Testing in HTML with `npm run test` in `html/` (100% coverage, 100% passing)
 - [ ] Unit Testing in Angular with `npm run test` in `angular/` (100% coverage, 100% passing)
 - [ ] Unit Testing in React with `npm run test` in `react/` (100% coverage, 100% passing)

### Browser Testing (current version and 1 prior)
  - [ ] Google Chrome
  - [ ] Google Chrome (Mobile)
  - [ ] Mozilla Firefox
  - [ ] Mozilla Firefox (Mobile)
  - [ ] Microsoft Internet Explorer 11 (only this specific version of IE)
  - [ ] Microsoft Edge
  - [ ] Apple Safari
  - [ ] Apple Safari (Mobile)
  
### Accessibility Testing
  - [ ] Axe browser extension
  - [ ] Jaws Inspect
  - [ ] VoiceOver (iOS) or Talkback (Android)

### Deploy Preview Reviewed and Approved
 - [ ] Design Team
 - [ ] Accessibility Team

### Screenshots
Add screenshots to help explain your PR if you'd like. However, this is not
expected.

2021-02-04 19:41 UTC, guern1kn approved these changes

2021-02-04 20:19 UTC, bobwise requested changes
Great job on this! Left a few comments.

2021-02-04 20:19 UTC, bobwise commented on angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.component.spec.ts
> +  it('should href value if href is set on choice item', () => {
```suggestion
  it('should set href value if href is set on choice item', () => {
```

2021-02-04 20:19 UTC, bobwise commented on angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.component.spec.ts
> +  it('should href value if routerLink is set on choice item', () => {
```suggestion
  it('should set href value if routerLink is set on choice item', () => {
```

2021-02-04 20:19 UTC, bobwise commented on angular/projects/spark-angular/src/lib/components/sprk-footer/sprk-footer.component.spec.ts
> +      'sprk-o-CenteredColumn sprk-o-Stack sprk-o-Stack--misc-b sprk-c-Footer sprk-u-pam sprk-u-man',
I think we should add some new tests for the new routerLink options.

2021-02-04 20:19 UTC, bobwise commented on angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.component.spec.ts
> +    );
Tests for more routerLink options. Do we need a test for logo-slot/logo-slot-router?

2021-02-04 20:21 UTC, afebbraro commented on angular/projects/spark-angular/src/lib/components/sprk-award/sprk-award.component.spec.ts
> +    component.imgTwoHref = '/test';
In the component file, if imgTwoHref is not set, then there is no image. This fixes an old test.

2021-02-05 00:57 UTC, bobwise approved these changes

2021-02-05 15:14 UTC, merged