Tooltip Width bug
sparkdesignsystem/spark-design-system pull request #3863
Opened 2021-02-15 17:58 UTC by guern1kn

## What does this PR do?
A clear and concise description of what this PR does.

### Associated Issue
Fixes #3806 

## Please check off completed items as you work.
If a checklist item or section does not apply to your PR then please remove it.

### Documentation
 - [ ] Update Spark Docs

### Code
 - [ ] Build Component in HTML
 - [ ] Build Component in Angular
 - [ ] Build Component in React
 - [ ] Unit Testing in HTML with `npm run test` in `html/` (100% coverage, 100% passing)
 - [ ] Unit Testing in Angular with `npm run test` in `angular/` (100% coverage, 100% passing)
 - [ ] Unit Testing in React with `npm run test` in `react/` (100% coverage, 100% passing)

### Browser Testing (current version and 1 prior)
  - [ ] Google Chrome
  - [ ] Google Chrome (Mobile)
  - [ ] Mozilla Firefox
  - [ ] Mozilla Firefox (Mobile)
  - [ ] Microsoft Internet Explorer 11 (only this specific version of IE)
  - [ ] Microsoft Edge
  - [ ] Apple Safari
  - [ ] Apple Safari (Mobile)
  
### Accessibility Testing
  - [ ] Axe browser extension
  - [ ] Jaws Inspect
  - [ ] VoiceOver (iOS) or Talkback (Android)

### Deploy Preview Reviewed and Approved
 - [ ] Design Team
 - [ ] Accessibility Team

### Screenshots
Add screenshots to help explain your PR if you'd like. However, this is not
expected.

2021-02-22 14:37 UTC, afebbraro requested changes
Could you add in that window check I pasted on the issue?

2021-02-22 17:16 UTC, bobwise commented
I am still seeing the bug in macOS Safari and iOS Safari using this test app (without text zoom) https://jolly-raman-0e3a89.netlify.app/

2021-03-01 18:39 UTC, bobwise commented on html/components/tooltip.js
> +  );
Thank you for fixing this!

2021-03-01 18:40 UTC, bobwise approved these changes

2021-03-03 21:13 UTC, afebbraro approved these changes

2021-03-03 21:33 UTC, merged