#1412 - bug - Fix HTML toggle to look at other triggers for click eve…
sparkdesignsystem/spark-design-system pull request #3874
Opened 2021-02-17 23:02 UTC by jmrieger

…nts, not just click

## What does this PR do?
Solves a race condition in HTML Spark, where using the spacebar to trigger toggle events would not honor the state of the toggle.

### Associated Issue
https://github.com/sparkdesignsystem/Backlog/issues/1412

## Please check off completed items as you work.
If a checklist item or section does not apply to your PR then please remove it.

### Documentation

### Code
 - [x] Build Component in HTML
 - [x] Unit Testing in HTML with `npm run test` in `html/` (100% coverage, 100% passing)

### Browser Testing (current version and 1 prior)
  - [x] Google Chrome
  - [ ] Google Chrome (Mobile)
  - [ ] Mozilla Firefox
  - [ ] Mozilla Firefox (Mobile)
  - [ ] Microsoft Internet Explorer 11 (only this specific version of IE)
  - [ ] Microsoft Edge
  - [ ] Apple Safari
  - [ ] Apple Safari (Mobile)
  
### Accessibility Testing
  - [ ] Axe browser extension
  - [ ] Jaws Inspect
  - [ ] VoiceOver (iOS) or Talkback (Android)

### Deploy Preview Reviewed and Approved
 - [ ] Design Team
 - [ ] Accessibility Team

### Screenshots
See the attached bug in the backlog for a video of the behavior prior to this fix.

2021-02-22 18:17 UTC, bobwise commented
Thank you @jmrieger!

2021-02-22 18:18 UTC, bobwise approved these changes

2021-02-22 18:19 UTC, RVMendoza approved these changes
That makes sense to me as well! Thank so much for this contribution @jmrieger. Really tightens up the experience.

2021-02-22 18:23 UTC, guern1kn approved these changes

2021-02-22 19:17 UTC, afebbraro requested changes
Thanks for the PR @jmrieger ! Good stuff! We are just going to get a test added for this. @bobwise  will reach out to you.

2021-02-23 18:56 UTC, afebbraro commented
Thanks for adding in that test!! @bobwise, is the PR ready to merge?

2021-02-23 19:30 UTC, bobwise approved these changes

2021-02-23 20:34 UTC, afebbraro approved these changes

2021-02-23 20:35 UTC, merged