Add compact buttons
sparkdesignsystem/spark-design-system pull request #4034
Opened 2021-07-15 20:04 UTC by rachelsuter

## What does this PR do?
Adds compact buttons (primary, secondary, and tertiary) to each storybook.

### Associated Issue
2416142

2021-07-19 15:21 UTC, bobwise approved these changes
Great job @rachelsuter!!

2021-07-19 16:48 UTC, guern1kn requested changes
Great job on this, Rachel! I have a small update for you to make on the React stories, but then I'll approve!

2021-07-19 16:48 UTC, guern1kn commented on react/src/components/buttons/SprkButton.stories.js
> +  <SprkButton
Let's go through and update all the button stories in here to be in order. There's no `button-4` or `button-8` so let's just update everything and have the numbers match on the `idString` and the `analyticsString` for each button.

2021-07-20 14:50 UTC, afebbraro requested changes
Thanks for the PR! I left a comment for the file.

2021-07-20 14:50 UTC, afebbraro commented on angular/projects/spark-angular/src/lib/directives/sprk-button/sprk-button.stories.ts
> +      additionalClasses="sprk-c-Button--compact"
This is a directive so you would use just `class` here instead of needing to use the addtionalClasses input.

2021-07-20 19:02 UTC, guern1kn approved these changes
Great job, Rachel!

2021-07-22 15:22 UTC, afebbraro approved these changes

2021-07-22 15:22 UTC, merged