Rm updates
sparkdesignsystem/spark-design-system pull request #4043
Opened 2021-07-28 14:26 UTC by guern1kn

## What does this PR do?
RM Updates

### Associated Issue
Fixes 2256511

2021-07-28 19:55 UTC, afebbraro requested changes
Looks good, just found one typo.

2021-07-28 19:55 UTC, afebbraro commented on angular/projects/spark-angular/src/lib/components/sprk-footer/sprk-footer.component.spec.ts
> +        imgAlt: 'Rocket Mortgage by Rocket Mortgage Logo',
Think this one might of been a typo.

2021-07-28 19:56 UTC, guern1kn commented on angular/projects/spark-angular/src/lib/components/sprk-footer/sprk-footer.component.spec.ts
> +        imgAlt: 'Rocket Mortgage by Rocket Mortgage Logo',
Yup! Good catch.

2021-07-28 20:04 UTC, afebbraro approved these changes

2021-08-01 16:02 UTC, yodasw16 approved these changes

2021-08-01 16:03 UTC, merged